utilities: upcall_monitor: Avoid optimizing size.
Use the barrier trick to avoid clang from optimizing the 'size' variable
that can cause the verifier to think that 'size' can be negative:

./upcall_monitor.py
119: (85) call bpf_probe_read_kernel#113
R2 min value is negative, either use unsigned or 'var &= const'
processed 131 insns (limit 1000000) max_states_per_insn 0 total_states
peak_states 9 mark_read 3
Traceback (most recent call last):
File "/ovs/utilities/usdt-scripts/./upcall_monitor.py", line 729, in
odule>
main()
File "/ovs/utilities/usdt-scripts/./upcall_monitor.py", line 697, in
in
b = BPF(text=source, usdt_contexts=usdt, debug=options.debug)
File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 373, in
init__
self._trace_autoload()
File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 1241, in
race_autoload
fn = self.load_func(func_name, BPF.KPROBE)
File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 412, in
ad_func
raise Exception("Failed to load BPF program %s: %s" %
Exception: Failed to load BPF program b'kretprobe__ovs_dp_upcall':
permission denied.

Signed-off-by: Adrian Moreno <amorenoz@redhat.com>